### ISSUE TITLE
Udacity Review

### ISSUE THREAD

**Issue by madhur-taneja** [gwizamaryse/Project-2--Landing-Page#1]
Hey @gwizamaryse 

I'm the reviewer who reviewed your project and I'm glad you left your Github link in the comments. To justify my review and clarify your doubts that you mentioned in your comments, 

![rating](https://user-images.githubusercontent.com/24964149/84296206-51c4f700-ab69-11ea-9f36-6993040fedc1.PNG)

here's an explanation:

1. Yes, of course, the active state works perfectly both on my local system and your GitHub hosted environment but as I mentioned in the review, the section tags should also have an active state. I think this caused some misunderstandings. The different sections that you have on your page should also have some kind of active class added to them when they are in the viewport and not just nav links which work perfectly fine as you mentioned.

2. To explain why your navbar wasn't responsive, I'm attaching a GIF that shows how your navbar responds when I added a few more sections to it through dev tools and also through the `index.html` file.

![Responsiveness](https://user-images.githubusercontent.com/24964149/84296714-0bbc6300-ab6a-11ea-906c-85301d3f9b9c.gif)
. 
As you might notice, the nav links for Section 5,6,7 are not visible. This is because the navbar isn't adaptive to it. What I suggested in the review was to add a hamburger icon so which is the conventional way to make a navbar responsive so that no matter how many sections are there on the page, they will be visible when a user expands the navbar. Refer [this](https://codepen.io/impondesk/pen/EaKoXY) link for a working example that uses bootstrap. You have to build something similar using Flexbox and Grids.

Please do let me know if you still don't fully understand what I mentioned above. Thanks.

Best,
Madhur

**Comment by gwizamaryse** [comment]
hey  @madhur-taneja madhur-taneja 

thank you  for taking the time to write your feedback. I did not really get it the first time. 

Its clearer now. I will accordingly correct my project. 

Thank you 

Maryse

**Comment by madhur-taneja** [comment]
Hi again, 

I'm happy that it's clearer now. And I would really appreciate it if you could change the rating you provided as it's affecting my overall rating a lot 'cause I believe that the review I provided you was accurate and important to be corrected as per the rubrics for the sake of your better learning. Udacity takes ratings very seriously and your one small action will be very beneficial for me. Thanks in advance. 

Madhur
